# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b6d7ff2165649f8fdf8a4cd41596cfb0e00a26fad9823717295a4fa05262b3f7650d7b3dbfd8019baf375713f291535187015c4bd511ea5b2e2faab55cb220

test:
  secret_key_base: 386776c30dc50e794f27112e0c0c00ff08f146162c4b510c444d9e30e13524e9460cfbbaa854a5bdf27868e3d3a0f2371d22a1d4448f60c6ad39a9010fb49c91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
